#+title: Clean Init

Keeping this separate from my doom-emacs config for now.
Loading it with emacs -q -l. That's why it's tangling to something that isn't in ~/.config/emacs

* Emacs-forge Init
:PROPERTIES:
:visibility: children
:header-args: emacs-lisp :tangle ~/emacs-forge/init.el :mkdirp yes
:END:
** Lexical Binding
This stuff goes at the top of the file. Just yak-shaving.
#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t -*-
#+end_src
** Bootstrapping Straight.el
*** Early-Init
Disables use-package. This block tangles to early-init.el
#+begin_src emacs-lisp :tangle ~/emacs-forge/early-init.el :mkdirp yes
  ;;; -*- lexical-binding: t -*-
  (setq package-enable-at-startup nil)
#+end_src
*** Bootstrap code
Code required to set-up and use straight.el instead of use-package. 
Installs use-package (package configuration syntax I'm used to) but then has any use-package calls made to straight.el instead.
#+begin_src emacs-lisp
  (defvar bootstrap-version)
   (let ((bootstrap-file
          (expand-file-name
           "straight/repos/straight.el/bootstrap.el"
           (or (bound-and-true-p straight-base-dir)
               user-emacs-directory)))
         (bootstrap-version 7))
     (unless (file-exists-p bootstrap-file)
       (with-current-buffer
           (url-retrieve-synchronously
            "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
            'silent 'inhibit-cookies)
         (goto-char (point-max))
         (eval-print-last-sexp)))
     (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src
** Packages
*** Evil and its Evil Ecosystem
Mwahahaha.

evil-undo, by default, undoes everything since the last time you entered insert mode. fine-undo will use smaller changes as undo steps.

undo-limit is set really, really high because this isn't 1985 anymore and I don't have to account for the use of every byte

#+begin_src emacs-lisp
  (use-package evil
      :init
      (setq evil-want-fine-undo t
            undo-limit 900000
            evil-want-integration t
            evil-want-keybinding nil
  	  evil-undo-system 'undo-fu)
      :config
      (evil-mode 1))

    (use-package evil-collection
      :after evil
      :config
      (evil-collection-init))

    (use-package evil-goggles)
#+end_src
*** Vertico/Swiper/Orderless/Consult/Marginalia
Completion Stack Plus Swiper.

I use swiper since it seems like you need to do extra work to make consult-line work like swiper. Future task TODO.
#+begin_src emacs-lisp
  (use-package swiper)
  (use-package vertico
    :config
    (setq vertico-cycle t)
    (setq vertico-resize nil)
    (vertico-mode 1))
  (use-package orderless
    :custom
    (completion-styles '(orderless basic)))
  (use-package consult
    :config
    (add-to-list 'consult-buffer-filter "^\\*")) ;; hides temp files from consult-buffer
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src
*** Modeline
I'd like to configure this some more
#+begin_src emacs-lisp
  (use-package doom-modeline
    :custom
    (doom-modeline-height 20)
    (doom-modeline-hud t)
    :init (doom-modeline-mode 1))
#+end_src
*** Which-key
#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 0.3))
#+end_src
*** Hydra
Provides transient keybindings. This seems very useful, need to investigate more. Already getting a lot of use out the sample one.

#+begin_src emacs-lisp
(use-package hydra)

(defhydra hydra-text-scale (:timeout 4)
  "scale text"
  ("o" text-scale-increase "in")
  ("k" text-scale-decrease "out")
  ("f" nil "finished" :exit t))
#+end_src
*** Flycheck
Not fully configured yet; but this will get basic syntax checking done.

#+begin_src emacs-lisp
(use-package flycheck
  :diminish flycheck-mode
  :config
  (flycheck-mode t))
#+end_src
*** Helpful
Code pulled from dirty-init.el based from EFS. I don't use counsel anymore, so I need to investigate if I still want this.

#+begin_src emacs-lisp
;; (straight-use-package 'helpful
;;   :ensure t
;;   :custom
;;   (counsel-describe-function-function #'helpful-callable)
;;   (counsel-describe-variable-function #'helpful-variable)
;;   :bind
;;   ([remap describe-function] . counsel-describe-function)
;;   ([remap describe-command] . helpful-command)
;;   ([remap describe-variable] . counsel-describe-variable)
;;   ([remap describe-key] . helpful-key))
#+end_src
*** Magit
Is it Mag-it or Maggot?

Throws an error when loaded right now. Too tired to figure out what's going on so will just disable it for now and use git in terminal.
#+begin_src emacs-lisp
;; (use-package magit)
#+end_src
*** Assorted other packages
#+begin_src emacs-lisp
  (use-package vterm)
  (use-package fish-mode)
  (use-package smartparens
    :hook
    (prog-mode . smartparens-mode))
  (require 'smartparens-config)
  (use-package general) ;; for binding. binds declared later in the file
  (use-package docker-compose-mode)
  (use-package systemd)
  (use-package hl-todo
    :hook
    (org-mode . hl-todo-mode))
  (use-package undo-fu)
  (use-package spacious-padding
    :config
    (spacious-padding-mode))
#+end_src
** Org and Org-Ecosystem
Lets be honest here, this is the real star of the show
*** Org
#+begin_src emacs-lisp
(use-package org ;; makes org happen
      :custom
      (org-startup-with-inline-images t)
      (org-startup-indented t)
      (org-startup-folded t))

(use-package org-modern ;; makes org pretty
      :custom
      (org-modern-star '("◉" "○" "◈" "◇" "*" "◇" "*"))
      (org-ellipsis " ▼")
      (org-auto-align-tags nil)
      (org-tags-column 0)
      (org-fold-catch-invisible-edits 'show-and-error)
      (org-special-ctrl-a/e t)
      (org-insert-heading-respect-content t)
      (org-hide-emphasis-markers t)
      (org-pretty-entities t)
      :config
      (global-org-modern-mode))

   (use-package org-appear ;; makes org a bit sneakier
      :hook
      (org-mode . org-appear-mode)
      :custom
      (org-hide-emphasis-markers t)
      (org-appear-autolinks 'just-brackets))

#+end_src
*** Org-Babel
TODO: Work in progress

Org-autocomplete structure templates. typing < and then a two-letter code will fill in the rest of that entry, eg <el will replace with src emacs-lisp

#+begin_src emacs-lisp
    (with-eval-after-load 'org
      (org-babel-do-load-languages
       'org-babel-load-languages
       '((emacs-lisp . t))))

  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("fi" . "src fish"))
  (add-to-list 'org-structure-template-alist '("co" . "src conf-unix"))
  (add-to-list 'org-structure-template-alist '("cs" . "src css"))
  (add-to-list 'org-structure-template-alist '("js" . "src json"))
  (add-to-list 'org-structure-template-alist '("sd" . "src systemd"))
  (add-to-list 'org-structure-template-alist '("dc" ."docker-compose-mode"))

#+end_src
*** Org-Roam
This is still a work in progress. I'm transitioning (heh) to org-roam and am working on building this environment.

Binds are all declared later.
#+begin_src emacs-lisp
  (use-package org-roam
    :custom
    (org-roam-directory "~/org/roam")
    :config
    (org-roam-db-autosync-enable))
#+end_src
**** Org-Roam Capture Templates
I'm still working on these.

#+begin_src emacs-lisp
(setq org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)
     ("b" "book notes" plain
       "\n* Source\n\nAuthor: %^{Author}\nTitle: ${title}\nYear: %^{Year}\n\n* Summary\n\n%?"
      :if-new (file+head "book-notes/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unnarrowed t)
     ("l" "linux notes" plain
      "\n* %^{Subject}\n\n%?"
      :if-new (file+head "linux-notes/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
      :unarrowed t)

     ))

#+end_src
** User Interface
*** Simple Tweaks
This is all simple tweaks and stuff that I prefer. 
#+begin_src emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit) ;; makes ESC a global quit

  ;; hides and tweaks UI elements
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (tooltip-mode -1)
  (set-fringe-mode 20)

  ;; enables non-destructive word-wrap globally
  (global-visual-line-mode)
  (global-word-wrap-whitespace-mode t)

  (global-hl-line-mode)
  (setq inhibit-startup-message t)
  (setq sentence-end-double-space nil)
  (setq save-interprogram-paste-before-kill t)
  (setq shell-file-name "/bin/fish"
        sh-shell "/bin/fish")
  (setq help-window-select t) ;; switch to help buffer on open
  (setq recentf-mode t)
  (setq scroll-margin 5)
#+end_src
*** Line Numbers
Enable lines numbers globally, then disables them for certain modes. Easier to do it that way than having to add a hook if I ever add new modes I want line numbers in. 
#+begin_src emacs-lisp
(global-display-line-numbers-mode t)
(dolist (mode '(org-mode-hook
                term-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src
*** Theme
Yeah, it's catppuccin. I'm basic.
#+begin_src emacs-lisp
(use-package catppuccin-theme
  :custom
  (catppuccin-flavor 'macchiato))
(load-theme 'catppuccin t)
#+end_src
*** Fonts and related
Set font to Fira Mono. Install all-the-icons (if not found)

TODO: Variable-width-font. I need to learn how stock emacs sets fonts since I don't use doom anymore.

TODO: Do I need different settings for laptop vs desktop?

#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "Fira Mono" :height 110)

(use-package all-the-icons
  :if (display-graphic-p)
  :init
  (unless (find-font (font-spec :name "all-the-icons"))
    (all-the-icons-install-fonts t)))

(use-package all-the-icons-dired
  :if (display-graphic-p)
  :hook (dired-mode . all-the-icons-dired-mode))

(use-package all-the-icons-completion
  :if (display-graphic-p)
  :init (all-the-icons-completion-mode)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup))
#+end_src
** Binds
*** Space as Leader and submenus
#+begin_src emacs-lisp
  (general-create-definer mei/leader-keys
    :keymaps '(normal insert visual emacs)
    :prefix "SPC"
    :global-prefix "M-SPC")
  (mei/leader-keys
   "f" '(:ignore f :which-key "file")
   "fs" '(save-buffer :which-key "save buffer")
   "ff" '(find-file :which-key "open file")
   "fr" '(consult-recent-file :which-key "recent file")

   "b" '(:ignore b :which-key "buffer")
   "bb" '(consult-buffer :which-key "switch buffer")
   "bk" '(kill-current-buffer :which-key "kill buffer")
   "bl" '(evil-switch-to-windows-last-buffer :which-key "last buffer")
   "bz" '(bury-buffer :which-key "bury buffer")
   "bx" '(scratch-buffer :which-key "scratch buffer")

   "s" '(:ignore s :which-key "search")
   "sb" '(swiper :which-key "search buffer")
   "sm" '(bookmark-jump :which-key "jump to bookmark")
   "sM" '(bookmark-set :which-key "set a bookmark")

   "e" '(:ignore e :which-key "eval")
   "e;" '(eval-expression :which-key "expression")
   "ee" '(eval-last-sexp :which-key "eval last expression")
   "eb" '(eval-buffer :which-key "eval buffer")

   "q" '(:ignore q :which-key "quit and session")
   "qq" '(save-buffers-kill-terminal :which-key "quit emacs")

   "h" '(:ignore h :which-key "help")
   "hf" '(describe-function :which-key "describe function")
   "hk" '(describe-key-briefly :which-key "describe key briefly")
   "hK" '(describe-key :which-key "describe key full")
   "hv" '(describe-variable :which-key "describe variable")

   "c" '(:ignore c :which-key "comments")
   "cr" '(comment-or-uncomment-region :which-key "comment region")
   "cl" '(comment-line :which-key "comment line")

   "w" '(:ignore w :which-key "window")
   "wq" '(evil-quit :which-key "evil-quit")
   "wT" '(tear-off-window :which-key "tear off window")

   "g" '(magit-status :which-key "magit")

   "r" '(:ignore r :which-key "org-roam")
   "r i" '(org-roam-node-insert :which-key "insert org-roam node")
   "r f" '(org-roam-node-find :which-key "find org-roam node")
   "r l" '(org-roam-buffer-toggle :which-key "toggle org-roam buffer")
   )
#+end_src
*** Global Keybinds
These are keybinds I want to work no matter what mode I'm in. As such, they're sparsely used. 
#+begin_src emacs-lisp
  (general-define-key
   :keymaps 'global
   "M-y" 'consult-yank-pop ;; paste (text)
   "M-Y" 'yank-media ;; paste (media)
   "M-w" 'kill-ring-save ;; copy
   "M-W" 'kill-region ;; cut (selection)
   "<f2>" 'hydra-text-scale/body
   "C-x <deletechar>" 'kill-sentence)
#+end_src
*** Other Keybinds
This is probably some kind of heresy, but I just can't do the hjkl movement. My fingers are too trained to seek out a WASD shape. evil-open-below has been moved to M-o since it's still useful.

My brain is too hardwired to have undo/redo on anything but C-z/y.

A bunch of other minor changes for navigation. 
#+begin_src emacs-lisp
  (general-define-key
   :states 'normal
   "o" 'evil-previous-visual-line
   "k" 'evil-backward-char
   ";" 'evil-forward-char
   "l" 'evil-next-visual-line
   "C-_" 'evil-emacs-state
   "M-o" 'evil-open-below)

  (general-define-key
   :states '(normal insert)
     "C-z" 'evil-undo
     "C-y" 'evil-redo
     "C-e" 'evil-forward-sentence-begin)

#+end_src
* Tangle on Save
:PROPERTIES:
:header-args: emacs-lisp :tangle ~/emacs-forge/init.el :mkdirp yes
:END

I found this function from Emacs-From-Scratch. You have to manually tangle yourself the first time to get the function into your init.el. Once it's loaded then everytime you save this file, it will auto-tangle to the destinations. 

#+begin_src emacs-lisp :tangle ~/emacs-forge/init.el :mkdirp yes

(defun efs/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/emacs-forge/clean-init.org"))
    ;; Dynamic scoping to the rescue
      (org-babel-tangle)))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
#+END_src

